load("@io_bazel_rules_go//go:def.bzl", "go_prefix", "go_library", "go_test", "cgo_library")

go_prefix("github.com/jmhodges/cld2")

cgo_library(
    name = "cgo_default_library",
    srcs = [
        "cld2.cc",
        "cld2.go",
        "cld2.h",
        "cld2_dynamic_compat.h",
        "cld2_dynamic_data.h",
        "cld2_dynamic_data_extractor.h",
        "cld2_dynamic_data_loader.h",
        "cld2_generated_cjk_compatible.cc",
        "cld2_generated_deltaocta0122.cc",
        "cld2_generated_distinctocta0122.cc",
        "cld2_generated_quad0122.cc",
        "cld2tablesummary.h",
        "cld_generated_cjk_delta_bi_32.cc",
        "cld_generated_cjk_uni_prop_80.cc",
        "cld_generated_score_quad_octa_0122.cc",
        "cldutil.cc",
        "cldutil.h",
        "cldutil_offline.h",
        "cldutil_shared.cc",
        "cldutil_shared.h",
        "compact_lang_det.cc",
        "compact_lang_det.h",
        "compact_lang_det_hint_code.cc",
        "compact_lang_det_hint_code.h",
        "compact_lang_det_impl.cc",
        "compact_lang_det_impl.h",
        "debug.cc",
        "debug.h",
        "encodings.h",
        "fixunicodevalue.cc",
        "fixunicodevalue.h",
        "generated_distinct_bi_0.cc",
        "generated_entities.cc",
        "generated_language.cc",
        "generated_language.h",
        "generated_ulscript.cc",
        "generated_ulscript.h",
        "getonescriptspan.cc",
        "getonescriptspan.h",
        "integral_types.h",
        "lang_script.cc",
        "lang_script.h",
        "langspan.h",
        "offsetmap.cc",
        "offsetmap.h",
        "port.h",
        "scoreonescriptspan.cc",
        "scoreonescriptspan.h",
        "stringpiece.h",
        "tote.cc",
        "tote.h",
        "unittest_data.h",
        "utf8acceptinterchange.h",
        "utf8prop_lettermarkscriptnum.h",
        "utf8repl_lettermarklower.h",
        "utf8scannot_lettermarkspecial.h",
        "utf8statetable.cc",
        "utf8statetable.h",
    ],
    visibility = ["//visibility:public"],
)

go_library(
    name = "go_default_library",
    srcs = [],
    library = ":cgo_default_library",
    visibility = ["//visibility:public"],
)

go_test(
    name = "go_default_test",
    srcs = ["cld2_test.go"],
    library = ":go_default_library",
)
